# https://github.com/awslabs/serverless-application-model/blob/develop/versions/2016-10-31.md
# Indentation needs to be set with spaces, because YAML...
AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Lambda function that builds Duels stats on a regular schedule

Resources:
    BuildDuelsStatsFunction:
        Type: AWS::Serverless::Function
        Properties:
            Handler: build-duels-stats.default
            Runtime: nodejs10.x
            Timeout: 900
            CodeUri: ./dist/build-duels-stats
            MemorySize: 128
            Policies:
                - AWSLambdaVPCAccessExecutionRole
                - AmazonSESFullAccess
                - SecretsManagerReadWrite
                - AmazonSNSReadOnlyAccess
                # - arn:aws:iam::478062583808:policy/CloudWatchPolicyForLambda # See https://stackoverflow.com/questions/51166504/disable-cloudwatch-to-monitor-logs-for-lambda-function
            Tags:
                LambdaName: cron-build-duels-stats
            Events:
                # Populate the info on the last hour
                LastPeriodTrigger:
                    Type: Schedule
                    Properties:
                        Schedule: cron(0 2 * * ? *) # Triggers every day at 1 AM
